---
# List of mounts to disable
# Uses ansible.posix.mount module
mount_setup_disable:
#  - path: /mnt/temp
#    state: unmounted

# List of mounts to enable
# Uses ansible.posix.mount module
mount_setup_enable:
#  - src: 192.168.122.1:/export
#    path: /mnt/remote
#    fstype: nfs
#    opts: _netdev,hard
#    state: mounted
