---
galaxy_info:
  role_name: ima_evm_setup
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: ima_evm_setup role
  license: GPLv3+
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []
