---
galaxy_info:
  role_name: packages_verify
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: packages_verify role
  license: GPLv3+
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []

allow_duplicates: true
