---
# Install or remove server VM guest agents
# This role will detect and enable correct
# agent and remove other agents if present
# Will uninstall all agents if set to false
# NB. Only agents from RHEL repositories
#     are considered for un/installation
guest_agent_enable: true

# Remove unneeded firmware packages on VMs
# VMs with device passthrough may need these
guest_agent_remove_firmware: true
