---
# List of files and directories to copy
# Uses Ansible built-in copy module
# Registers variable: copy_files
files_copy:
#  - src: /local/path/test.file
#    dest: /tmp/test.file
#    mode: '0600'

# List of templates to render
# Uses Ansible built-in template module
# Registers variable: copy_templates
files_copy_templates:
#  - src: settings.conf.j2
#    dest: /etc/settings.conf
#    mode: '0644'
