---
splunk_deployment_server:
splunk_deployment_server_port: 8089
splunk_deployment_server_check: true

# Local 'splunk' user UID to use. A local user
# will be created if no local/remote user exists
# Set to undefined/none to create system account
splunk_user_uid: 4445
# This should come from vault
#splunk_user_password_hash:

splunk_phonehome_secs: 600

# Allowed states: present, latest
splunk_forwarder_package_state: present

# Deployment and user configuration templates
# to use if not using the role provided defaults
splunk_deployment_config_file:
splunk_user_config_file:
