---
galaxy_info:
  role_name: fips_setup
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: fips_setup role
  license: GPLv3+
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []
