---
packages_remove:
  - gofer
  - katello-agent
  - puppet-agent
  - rhn*
  - telnet-server

  #- biosdevname
  #- cloud-init
  #- flashrom
  #- fonts*
  #- gawk-all-langpacks
  #- geolite*
  #- hwdata
  #- kernel-tools*
  #- libicu
  #- libjpeg*
  #- linux-firmware-whence
  #- lshw
  #- NetworkManager-tui
  #- nfs*
  #- libnfs*
  #- parted
  #- rpc*
  #- sssd*
  #- libsss*
  #- tcpdump
  #- teamd
  #- webkit*

# List of dnf excludes
packages_remove_exclude:
  - kernel
  - kernel-core
  - microcode_ctl

# Remove all "leaf" packages no longer required,
# see dnf module autoremove parameter description
packages_remove_autoremove: false

# Display results on output
packages_remove_display_results: false
